version: '3.7'

services:
  server:
    build: 
      context: ./
      target: production-build-stage
      dockerfile: Dockerfile
    image: lotmanager-api
    container_name: server
    ports:
    - 5000:5000
    volumes:
      - ./.env:/.env
    restart: unless-stopped

